import "@rainbow-me/rainbowkit/styles.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "../hooks/ThemeProvider";
import Navbar from "./Navbar";
import Footer from "@/components/Footer";
import { WalletProvider } from "../hooks/WalletProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HodlCoin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`min-h-screen flex flex-col bg-cover bg-center text-black bg-[#C8F4F9] dark:text-white dark:bg-[#0D1B2A]`}
    >
      <WalletProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Navbar */}
          <Navbar />

          {/* Main Content Area */}
          <main className="flex-grow flex flex-col items-center justify-start py-8">
            {children}
          </main>

          {/* Footer */}
          <Footer />
        </ThemeProvider>
      </WalletProvider>
    </div>
  );
}
